services:
  znote:
    container_name: znote
    image: likeflyme/znotetp:latest
    ports:
      - "3888:3888"
    volumes:
      - "./data:/app/data"
    restart: always
    environment:
      TZ: Asia/Shanghai
